spring:
  application:
    name: Loveable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
        format_sql:true


jwt:
  secretkey: bbvyuhuf7ry73ye83ue8u8eu9wue8ye8wububihd8y824ffedw3r532

stripe:
  secret: ${STRIPE_SECRET_KEY}

client.url: http://localhost:8080
